# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0003_auto_20181205_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='article',
            name='update_time',
        ),
    ]
